### ISSUE TITLE
remove taxa ranks from treatments facets

### ISSUE THREAD

**Issue by tcatapano** [plazi/BLR-website#11]
per https://github.com/plazi/BLR-website/blob/master/facets.md#treatments

**Comment by punkish** [comment]
removed

**Comment by teodorgeorgiev** [comment]
remove: 

SPECIES
GENUS
FAMILY
ORDER
PHYLUM
KINGDOM
JOURNALVOLUME

return back RANK (+ normalize the values)

**Comment by punkish** [comment]
fixed everything except issue14 (normalizing rank values)
