### ISSUE TITLE
BLR Website testing: taxon treatments have nothing to do with author

### ISSUE THREAD

**Issue by myrmoteras** [plazi/BLR-website#25]
Searching for "Agosti" I get all stuff which have nothing to do with Agosti, but may be I am mentioned somewhere which has nothing to do with treatments.

![image](https://user-images.githubusercontent.com/4609956/76784152-6b95ae80-67b3-11ea-923b-0a00243239e5.png)

This is irritating and not helpful. It is like the full text search over BHL, which we make specific beause we extract authors, taxa in the GGI process. We need to make use of the tagged data we have in TB or in the metadata in BLR. 
Thus agosti can show up as an author, authority, taxon

If we don't do this, then we ignore 15 years of development which sets us apart from the rest.

**Comment by punkish** [comment]
it is returning full text search because they are asking it to return fts. If you want `authorityName` (which, I believe is the author), then you need the following query

```
https://zenodeo.punkish.org/v2/treatments?communities=biosyslit&page=1&size=30&refreshCache=false&authorityName=Agosti&sortBy=treatmentId%3AASC&facets=false&stats=false&xml=false
```

which returns two entries

```json
{
  "value": {
    "search-criteria": {
      "authorityName": "Agosti",
      "communities": "biosyslit",
      "facets": "false",
      "page": "1",
      "size": "30",
      "sortBy": "treatmentId:ASC",
      "stats": "false",
      "xml": "false",
      "limit": 30,
      "offset": 0
    },
    "num-of-records": 2,
    "_links": {
      "self": {
        "href": "https://zenodeo.punkish.org/v2/treatments?authorityName=Agosti&;amp;communities=biosyslit&amp;facets=false&amp;page=1&amp;size=30&amp;sortBy=treatmentId:ASC&amp;stats=false&amp;xml=false"
      },
      "prev": {
        "href": "https://zenodeo.punkish.org/v2/treatments?authorityName=Agosti&;amp;communities=biosyslit&amp;facets=false&amp;page=0&amp;size=30&amp;sortBy=treatmentId:ASC&amp;stats=false&amp;xml=false"
      },
      "next": {
        "href": "https://zenodeo.punkish.org/v2/treatments?authorityName=Agosti&;amp;communities=biosyslit&amp;facets=false&amp;page=&amp;size=30&amp;sortBy=treatmentId:ASC&amp;stats=false&amp;xml=false"
      }
    },
    "records": [
      {
        "id": 27309,
        "treatmentId": "03A1879CFFD3FFB4CD75987266B6FD85",
        "treatmentTitle": "Cataglyphis hannae Agosti, 1994, n. sp.",
        "articleDoi": "10.5281/zenodo.2949937",
        "zenodoDep": "2949937",
        "zoobank": "",
        "articleTitle": "A new inquiline ant (Hymenoptera: Formicidae) in Cataglyphis and its phylogenetic relationship",
        "publicationDate": "1993-10-20",
        "journalTitle": "Journal of Natural History",
        "journalYear": "1994",
        "journalVolume": "28",
        "journalIssue": "",
        "pages": "913–919",
        "authorityName": "Agosti",
        "authorityYear": "1994",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "order": "Hymenoptera",
        "family": "Formicidae",
        "genus": "Cataglyphis",
        "species": "hannae",
        "status": "n. sp.",
        "taxonomicNameLabel": "n. sp.",
        "rank": "species",
        "_links": {
          "self": {
            "href": "https://zenodeo.punkish.org/v2/treatments?treatmentId=03A1879CFFD3FFB4CD75987266B6FD85"
          }
        }
      },
      {
        "id": 290452,
        "treatmentId": "E83A2C2AFF8DFFA5FF76FC9F5ADD6BFE",
        "treatmentTitle": "Probolomyrmex brujitae Agosti 1995",
        "articleDoi": "https://doi.org/10.11646/zootaxa.4614.1.3",
        "zenodoDep": "3241099",
        "zoobank": "E9C39B4E-D897-428C-B290-95EA40826D93",
        "articleTitle": "Taxonomic revision of the genus Probolomyrmex Mayr, 1901 (Hymenoptera: Formicidae: Proceratiinae) for the Neotropical Region",
        "publicationDate": "2019-06-07",
        "journalTitle": "Zootaxa",
        "journalYear": "2019",
        "journalVolume": "4614",
        "journalIssue": "1",
        "pages": "61–94",
        "authorityName": "Agosti",
        "authorityYear": "1995",
        "kingdom": "Animalia",
        "phylum": "Arthropoda",
        "order": "Hymenoptera",
        "family": "Formicidae",
        "genus": "Probolomyrmex",
        "species": "brujitae",
        "status": "",
        "taxonomicNameLabel": "",
        "rank": "species",
        "_links": {
          "self": {
            "href": "https://zenodeo.punkish.org/v2/treatments?treatmentId=E83A2C2AFF8DFFA5FF76FC9F5ADD6BFE"
          }
        }
      }
    ],
    "nextid": 290452,
    "from": 1,
    "to": 2,
    "previd": 0,
    "prevpage": 0,
    "nextpage": ""
  },
  "cached": null,
  "report": {
    "msec": 0.2842629551887512
  }
}
```

**Comment by punkish** [comment]
> If we don't do this, then we ignore 15 years of development which sets us apart from the rest.

it is not that bad :). Surely, we have a ton of problems with the data itself even after 15 years of development. Nevertheless, yes, we can should leverage what we have to the best. We will get there, no worries.

**Comment by myrmoteras** [comment]
@punkish did you check this from the website http://blr.uplaysandbox.website/ and not from your API?
![image](https://user-images.githubusercontent.com/4609956/76834274-26ae5e00-682d-11ea-8414-b908adb3ac14.png)

selecting anything like author has no impact on the result.

**Comment by punkish** [comment]
you are correct. There is an error in the website. It should have queried `authorityName=agosti` but instead, it queried `q=agosti`. Fixing that should get better results.

Also, a suggestion to the website makers – once you get and display the result, please also continue to display the state that caused that query, that is, in the above case, continue to show the "Author" radio button as selected instead of none selected. That is a nice little affordance for the user to remember what she/he searched for.

An additional suggestion to the website makers – query for *only* what you are going to use. I could be wrong in this, but as far as I see, you don't make use of `stats` so don't send the `stats=true` param to the server. Otherwise the server needlessly performs the query.
