### ISSUE TITLE
use authorityName parameter in Author queries

### ISSUE THREAD

**Issue by tcatapano** [plazi/BLR-website#29]
Creating issue from #25 

>you are correct. There is an error in the website. It should have queried `authorityName=agosti` but instead, it queried `q=agosti`. Fixing that should get better results.

_Originally posted by @punkish in https://github.com/plazi/BLR-website/issues/25#issuecomment-599940979_

**Comment by teodorgeorgiev** [comment]
The bug in the interface will be fixed. 
However, please note that 
https://zenodeo.punkish.org/v2/treatments?facets=true&authorityName=agosti
return 0 results.
@myrmoteras @punkish I guess the search should be case insensitive?

**Comment by punkish** [comment]
case-insensitive searches are now possible
