### ISSUE TITLE
BLR website URL is not updating with the query

### ISSUE THREAD

**Issue by punkish** [plazi/BLR-website#53]
I thought this was fixed, but I just now searched for chordata, got the results, clicked on a facet, got the results narrowed, all good. But the URL search bar remained unchanged (see image below). The URL should always display the state that the website is in. This is good from a semantic web pov, and also allows users to share or bookmark links.

Also, we should really have this running under `https` if for no other reason than it possibly makes Google happy when its robots go crawling websites

![image](https://user-images.githubusercontent.com/349242/81408116-f2746100-913c-11ea-868e-cc7c44ed1a9e.jpeg)

@teodorgeorgiev

**Comment by teodorgeorgiev** [comment]
the url was fixed - it was configured to be hidden on the production environment
The SSL will be installed next week
