### ISSUE TITLE
testing: search does not reset

### ISSUE THREAD

**Issue by myrmoteras** [plazi/BLR-website#57]
I am searchig for Erwin, and get the results. I then use the facets, and then change from All to aontehr button. I then get much less, as I got before I used the facets.

That means, I can only make more and more restricted searches.
There is no way I can reset to start again.

**Comment by myrmoteras** [comment]
When I remove the facets that is selected, then I am getting back to the original search.

**Comment by tcatapano** [comment]
Fixed. Closing.
