### ISSUE TITLE
Text blocks for Website

### ISSUE THREAD

**Issue by myrmoteras** [plazi/BLR-website#6]
here are textblocks for the new BLR webbsite. Please read through it and correct

https://docs.google.com/document/d/1KFXidMCHpj22FLa0WvLAl-tPSle37dSGU7AYBxq1jgE/edit#heading=h.7w4y38uyr1is

BLR Website: http://blr.uplaysandbox.website/about
BLR Website: mockup: https://github.com/plazi/BLR-website/issues/4

**Comment by punkish** [comment]
@myrmoteras @teodorgeorgiev @tcatapano please close this issue if it has been implemented
