### ISSUE TITLE
image and publication resource endpoints

### ISSUE THREAD

**Issue by punkish** [plazi/BLR-website#9]
@howkins and @teodorgeorgiev, please note that the images and publications endpoints return the data from Zenodo as is, that is, without any modifications. The only difference between querying Zenodo directly vs querying Zenodeo is that the latter has a couple of convenience variations built in – for example, publications can be narrowed by type aka as subtype in Zenodo (for example `publications?q=pilbara&type=taxonomictreatment`). Also, Zenodeo returns *only* open access records as opposed to Zenodo that returns everything.

The main point here is that I am not sure if I can create facets for you. That data is not available to me to query and prepare the values as it is for treatments (I have access to the entire treatments database, not the Zenodo database), I am going to give this more thought and discuss this with @slint as well. We should pick this up during the sprint.

**Comment by howkins** [comment]
Hello @punkish 
We rendered some part of data from images and publications endpoints but I think that we have a problem with zenodo resources because they have a rate limit 60 images per minute then return 429 status (too many requests).

**Comment by punkish** [comment]
> Hello @punkish
> We rendered some part of data from images and publications endpoints but I think that we have a problem with zenodo resources because they have a rate limit 60 images per minute then return 429 status (too many requests).

yes, we are aware of the rate limit. Don't worry, we will fix it. The main thing is to get the logic between my Zenodeo and your website solid.

I am still working on the facets for images and publications, but as I mentioned before, I am limited because I don't have the entire data with me. I can only do manipulations on what Zenodo returns to me. Also, the same thing applies to sorting the result. Zenodo allows limited sorting, and I can only use that. Nevertheless, i want to make sure that all the routes from Zenodeo are consistent in terms of syntax and logic. Still working on that. Thanks.

**Comment by punkish** [comment]
rate limit has been fixed, as I understand.
